enable_audio_bell no
dynamic_background_opacity yes
background_opacity 0.95
cursor_shape beam
mouse_hide_wait 1

font_family      Hack Nerd Font
bold_font        Hack Nerd Font Bold
italic_font      Hack Nerd Font Italic
bold_italic_font Hack Nerd Font Bold Italic

font_size 14
disable_ligatures never

macos_option_as_alt yes
